# Generated by Django 4.0.4 on 2022-08-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_employee_department_alter_employee_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='facility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.facilitydropdown'),
        ),
    ]
