# Generated by Django 4.0.4 on 2022-08-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_alter_employee_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.facilitydropdown'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
