# Generated by Django 4.0.4 on 2022-11-08 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0007_grouppermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
