# Generated by Django 4.0.4 on 2022-11-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_grouppermission_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPermission',
        ),
    ]
