# Generated by Django 4.1.7 on 2023-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_queryreports_facility_templete'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryreports',
            name='date_templete',
            field=models.BooleanField(blank=True, default=False, verbose_name='Date Template'),
        ),
    ]
