# Generated by Django 4.1.7 on 2023-03-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_queryreports_date_templete'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryreports',
            name='pharmacy_iaarc',
            field=models.BooleanField(blank=True, default=False, verbose_name='Pharmacy IAARC Dropdown'),
        ),
    ]
