# Generated by Django 4.1.7 on 2023-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_queryreports_pharmacy_iaarc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryreports',
            old_name='date_templete',
            new_name='date_template',
        ),
        migrations.RenameField(
            model_name='queryreports',
            old_name='facility_templete',
            new_name='facility_template',
        ),
        migrations.AddField(
            model_name='queryreports',
            name='time_template',
            field=models.BooleanField(blank=True, default=False, verbose_name='Time Template'),
        ),
    ]
