# Generated by Django 4.1.7 on 2023-03-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_rename_date_templete_queryreports_date_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryreports',
            name='dropdown_options_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Custom Dropdown Options's Name"),
        ),
        migrations.AddField(
            model_name='queryreports',
            name='dropdown_options_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Custom Dropdown Options's value"),
        ),
    ]
