# Generated by Django 4.1.7 on 2023-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_queryreports_dropdown_options_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryreports',
            name='dropdown_options_name',
            field=models.TextField(blank=True, null=True, verbose_name="Custom Dropdown Options's Name"),
        ),
        migrations.AlterField(
            model_name='queryreports',
            name='dropdown_options_value',
            field=models.TextField(blank=True, null=True, verbose_name="Custom Dropdown Options's value"),
        ),
    ]
