# Generated by Django 4.1.7 on 2023-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_queryreports_input_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryreports',
            name='comma_separated_function',
            field=models.BooleanField(blank=True, default=False, verbose_name='Comma Separate Function'),
        ),
        migrations.AddField(
            model_name='queryreports',
            name='textbox',
            field=models.TextField(blank=True, null=True, verbose_name='TextBox Tags'),
        ),
    ]
