# Generated by Django 4.1.7 on 2023-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_queryreports_comma_separated_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryreports',
            name='comma_separated_function',
        ),
    ]
