# Generated by Django 4.1.7 on 2023-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_remove_queryreports_comma_separated_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryreports',
            name='http_response',
            field=models.BooleanField(blank=True, default=False, verbose_name='Display Within Browser (No Download Option)'),
        ),
    ]
