# Generated by Django 4.1.7 on 2023-04-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_queryreports_http_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryreports',
            name='report_subheading',
        ),
        migrations.DeleteModel(
            name='NavSubHeadings',
        ),
    ]
